### ISSUE TITLE
Changing colorbar font size

### ISSUE THREAD

**Issue by retlaw-1** [dwhswenson/contact_map#108]
How do I go about chaning the font size of the colorbar? 

Using: 
`fig, ax = frame_contacts.residue_contacts.plot(figsize=(50,50),cmap="plasma")`
Increases the graph size but keeps the font size of the colorbar doesn't scale.
`plt.xlabel("Residue",fontsize=50)`
`_ = plt.ylabel("Residue",fontsize=50)`
`ax.xaxis.set_tick_params(labelsize=30)`
`ax.yaxis.set_tick_params(labelsize=30)`

![image](https://user-images.githubusercontent.com/7916996/111831077-dc870f00-88bc-11eb-96b6-25f759d6e0f2.png)

**Comment by dwhswenson** [comment]
The colorbar is actually another `Axes` within your `fig`. So the trick here is as simple as:

```python
fig.axes[1].yaxis.set_tick_params(labelsize=30)
```

although it's definitely not obvious that you'd find it there! `ax` is the same as `fig.axes[0]`.

As an aside, if you want to use the whole color space of the `plasma` color map, just give the parameter `vmin=0` to the `plot` function. (The details of this may change to make it easier in the future.)

**Comment by retlaw-1** [comment]
Thanks! That worked perfectly.
