### ISSUE TITLE
Discussion: Moving off of AppVeyor

### ISSUE THREAD

**Issue by dwhswenson** [dwhswenson/contact_map#119]
This issue is to discuss whether we should move away from AppVeyor as a testing platform. This is in part a response to problems in #118, although I've been thinking about this for a while.

Historically, we use AppVeyor because Travis-CI didn't have free Windows builds. Now we've moved from Travis-CI to GitHub Actions for our Linux builds. GitHub Actions does allow free Windows builds.

We also use two different build processes. The Linux builds install requirements with `pip`, getting packages from PyPI. The Windows builds use `conda-build`, getting packages from conda-forge. This can be nice because sometimes packages have slight differences in their dependencies (most frequently, they include some extras on conda-forge that don't come with the package when you install with `pip`). Testing both ensures that we aren't implicitly relying on something that only comes through one distribution mechanism.

The problems with the current Windows builds:

1. AppVeyor only allows one simultaneous build, so even running only 2 builds takes a while.
2. The actual build process (via conda-build) is slower on Windows, which exacerbates the problem of not having simultaneous builds.
3. With our current build process, we need to wait for AppVeyor to update Miniconda versions. Our build doesn't seem to work on their Miniconda38, and there is no Miniconda39. So we're limited to Python 3.7.
4. The conda-build based build is unnecessary. This is because I mimicked what MDTraj did. We don't actually need conda-build, since we're not compiling anything. We can install requirements with conda if we want. This will also get rid of the need for the recipe in devtools -- that recipe is completely independent of the conda forge feedstock recipe, and is only used for the AppVeyor build.

So I think it makes sense to move Windows builds over to GitHub Actions as well. I haven't used Windows builds on GHA yet, so I'd love to hear anyone else's experiences with it (@sroet, have you used that?)

A few specific points to consider:

* **Build matrix**: Which versions do we test against? I suggest only 2 (to keep build matrix smaller) and having those be the newest version of Python and the oldest NEP29-required version, and only testing against the release version of MDTraj (we test against development builds on Linux).
* **Where to get packages from**: I think we should drop conda-build, but maybe continue to get packages from conda.

Anything else to consider? Any thoughts on these?

**Comment by sroet** [comment]
> So I think it makes sense to move Windows builds over to GitHub Actions as well. I haven't used Windows builds on GHA yet, so I'd love to hear anyone else's experiences with it (@sroet, have you used that?)

I unfortunately did not yet have an excuse to tinker much (if anything) with GHA

> Which versions do we test against? I suggest only 2 (to keep build matrix smaller) and having those be the newest version of Python and the oldest NEP29-required version, and only testing against the release version of MDTraj (we test against development builds on Linux).

Seems fine by me

>  I think we should drop conda-build, but maybe continue to get packages from conda.

Definitely do `conda` to prevent strange build issues from `pip` trying to pull in newer `numpy` versions during build time (due to build isolation)(https://github.com/mdtraj/mdtraj/issues/1446)

**Comment by dwhswenson** [comment]
> Definitely do `conda` to prevent strange build issues from `pip` trying to pull in newer `numpy` versions during build time

We use `pip` in our current Linux builds, but we use a pre-PEP517 build process (discussed in our [installation docs](https://contact-map.readthedocs.io/en/latest/installing.html), which I had hoped could be simplified in the post-PEP517 era, but perhaps not?).

In using `conda` for some builds and `pip` for others, I was thinking of choderalab/openmmtools#304. Since then, I have entered the modern age and use `conda` and `brew`, so it's nice to use CI to add some diversity to the installation process.

**Comment by sroet** [comment]
> We use pip in our current Linux builds, but we use a pre-PEP517 build process (discussed in our installation docs, which I had hoped could be simplified in the post-PEP517 era, but perhaps not?).

It is possible, but only if all of our dependencies that build against numpy are hard-pinned to the lowest numpy they support (like I have done for mdtraj in https://github.com/mdtraj/mdtraj/pull/1619).

> In using conda for some builds and pip for others, I was thinking of choderalab/openmmtools#304. Since then, I have entered the modern age and use conda and brew, so it's nice to use CI to add some diversity to the installation process.

I am in favor of also testing `pip` at least once in our tes-suite, but I would prefer it to be a Linux build that runs the most recent version of all our dependencies (which should minimize the risk of having an older numpy at run-time than during build-time, which triggers the value errors). My preference for linux here is that I fell more comfortable recognizing `pep` build errors on UNIX than possible strange errors on windows build.

**Comment by dwhswenson** [comment]
I absolutely agree with keeping Windows builds as conda-only. Since our existing Linux builds already build with `pip`, I was thinking to keep it that way (rather than switching to conda for most). Here's the matrix I'm proposing:

```
OS=ubuntu, DEPS_FROM=pip, MDTRAJ=mdtraj-release, CONDA_PY=3.7
OS=ubuntu, DEPS_FROM=pip, MDTRAJ=mdtraj-release, CONDA_PY=3.8
OS=ubuntu, DEPS_FROM=pip, MDTRAJ=mdtraj-release, CONDA_PY=3.9
OS=ubuntu, DEPS_FROM=pip, MDTRAJ=mdtraj-dev, CONDA_PY=3.9
OS=windows, DEPS_FROM=conda, MDTRAJ=mdtraj-release, CONDA_PY=3.7
OS=windows, DEPS_FROM=conda, MDTRAJ=mdtraj-release, CONDA_PY=3.9
```

The principles behind it:

* Windows: deps from conda, check newest Python and oldest NEP29
* Linux: deps from pip, check all NEP29-supported Python versions
* One extra build with dev version of MDTraj; use Linux and newest Python

One other point: the `mdtraj-dev` label actually includes both the dev version of MDTraj and all optional packages, so optional packages are only tested on Linux and with the most recent Python in this matrix (which is also true in our current builds). In principle we could separate `MDTRAJ=['mdtraj-release', 'mdtraj-dev']` and `EXTRAS=['', 'with-extras']`, but I'm not sure the extra complexity is worth it (or that we necessarily need additional builds.)

I'm also suggesting dropping Python 3.6 from the testing matrix since the [NEP29 drop schedule](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule) had us dropping that over a year ago (June 23, 2020).

The matrix above is essentially the same as our current matrix, except dropping Py3.6 and adding Windows/Py3.9.

**Comment by sroet** [comment]
Seems like a solid plan, +1 from me (also on dropping python 3.6)
