### ISSUE TITLE
ContactMap/ContactFrequency on a set of individual pdb (not trajectory)

### ISSUE THREAD

**Issue by aparente-nurix** [dwhswenson/contact_map#59]
I'm working with protein-protein docking output and would like to use ContactMap/ContactFrequency to classify the contacts formed in a set of protein-protein complexes.

Basically, I have a condition (condition A) that leads to a set of protein-protein complexes. I have another condition (condition B) that leads to a different set of protein-protein complexes. 

I'd like to assess differences between the contacts formed in complexes under condition A and contacts formed in complexes under condition B. What would be the best way to do this? I have multi-structure PDB files for both condition A and condition B.

**Comment by sroet** [comment]
If I understand you correctly, and I am assuming that at least your systems are the same (so the same number and ordering of atoms between the pdbs).

I would do something like this:
```python
import mdtraj as md
from contact_map import ContactFrequency

#make lists of pdb filenames
A_pdbs = ["A1.pdb", "A2.pdb"]
B_pdbs = ["B1.pdb", "B2.pdb"]

# Load them as trajectories with mdtraj
A_trj = md.load(A_pdbs)
B_trj = md.load(B_pdbs)

# Make the 2 contact frequencies (which will be normalized to be from 0 to 1
# so it does not matter if A and B are not of equal length  
A_freq = ContactFrequency(A_traj)
B_freq = ContactFrequency(B_traj)

# Now make a difference
diff = A_freq-B_freq
```
For further analysis of the difference (`diff`) I would advice you to take a look at [our example notebooks](https://github.com/dwhswenson/contact_map/blob/master/examples/contact_map.ipynb).

Does this solve your issue?

**Comment by dwhswenson** [comment]
Two small additions to what @sroet wrote:

1. The `ContactFrequency` object requries a sequence of configurations. As a habit from my own background, we usually talk about these like they're a trajectory. But there is nothing that requires any sort of time correlation between these configurations. MDTraj will load a multi-structure PDB file as a "trajectory", so everything from that end should be fine. (If, instead of multiple PDBs `A1.pdb`, `A2.pdb`, you have a single `all_A.pdb`, just use `md.load("all_A.pdb")`.)

2. One important point here is how the "difference" is defined. Let's say you have 4 frames representing `A` and 8 frames representing `B`. Let's assume that a given contact is present in all 4 frames of `A` (100%) and 2 of the 8 in `B` (25%). In that case, `A_freq - B_freq` would give a result of `0.75` for that contact (100% - 25%). It is the difference in the *frequencies*; it doesn't go back to the raw counts of frames. I think this is what you want, but it's an easy point of confusion.

    The per-frame version is also possible, through `A_freq.subtract_contact_frequency(B_freq)` (which changes the values in `A_freq`). Caveat: that hasn't been tested for what happens if the values are negative (it was designed for rolling averages).

**Comment by aparente-nurix** [comment]
Excellent, thank you! Looks like I was on the right path. Is there any way to use query to isolate the contacts only formed at the protein-protein interface?

**Comment by dwhswenson** [comment]
> Excellent, thank you! Looks like I was on the right path. Is there any way to use query to isolate the contacts only formed at the protein-protein interface?

@aparente-nurix : Yes -- the `query` and `haystack` are the two sides of a contact (a contact between residue `A` and residue `B` indicates that `A` is in the query and `B` is in the haystack or vice versa). So if you have `protein_A` and `protein_B`, you should put the atoms from one as the query and the other as the haystack, and you'll only look for contacts that form the interface.

See [the documentation of MDTraj's atom selection language](http://mdtraj.org/1.9.3/atom_selection.html) for how to select the relevant atoms from protein A and protein B.

In early versions of this code, there was a big performance difference which meant that the query should be smaller than the haystack. I think that improvements by @sroet have made that unimportant, but it still doesn't hurt to make the query smaller than the haystack (in terms of picking which protein to call "A" and which to call "B").

BTW, note that our default behavior is to use heavy atoms for contacts, and to use a cutoff distance where residues are considered "in contact" if any atoms considered are within 0.45nm. When you're selecting atoms to focus on the two proteins, you will either want to exclude hydrogens (`"and symbol != 'H'"`) or change the cutoff radius (or possibly both, depending on your opinion of our 0.45nm cutoff). Details on customizing all of this are in the examples (especially https://contact-map.readthedocs.io/en/latest/examples/nb/contact_map.html)

**Comment by sroet** [comment]
@aparente-nurix Can this be closed or did any other issue(s) come up?

**Comment by aparente-nurix** [comment]
Didn't face any other issues on this front, closing this ticket. Thanks!
